// <auto-generated />
using System;
using DB.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(ToDoListItemDBContext))]
    partial class ToDoListItemDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Entities.ToDoListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte>("Order")
                        .HasColumnType("tinyint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("toDoListItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9778),
                            Description = "To jest opis zadania numer jeden",
                            IsDeleted = false,
                            Order = (byte)1,
                            Status = 0,
                            Title = "Pierwsze zadanie"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9862),
                            Description = "To jest opis zadania numer dwa",
                            IsDeleted = true,
                            Order = (byte)1,
                            Status = 2,
                            Title = "Drugie zadanie"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9875),
                            Description = "To jest opis zadania numer trzy",
                            IsDeleted = false,
                            Order = (byte)2,
                            Status = 2,
                            Title = "Trzecie zadanie"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9888),
                            Description = "To jest opis zadania numer cztery",
                            IsDeleted = false,
                            Order = (byte)3,
                            Status = 2,
                            Title = "4 zadanie"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9900),
                            Description = "To jest opis zadania numer pięć",
                            IsDeleted = false,
                            Order = (byte)4,
                            Status = 2,
                            Title = "5 zadanie"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2024, 5, 26, 12, 24, 21, 470, DateTimeKind.Utc).AddTicks(9944),
                            Description = "To jest opis zadania numer sześć",
                            IsDeleted = false,
                            Order = (byte)5,
                            Status = 2,
                            Title = "6 zadanie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
